# Generated by Django 5.0 on 2024-03-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='car_company_main_image')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sum_of_rates', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('number_of_rates', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCompanyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_companies')),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars')),
            ],
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pickup_location', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarReservationIdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_reservation_id_image')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('Economy', 'Economy'), ('Compact', 'Compact'), ('Mid_Size', 'Mid_Size'), ('Full_Size', 'Full_Size'), ('Luxury', 'Luxury'), ('SUV', 'SUV'), ('Minivan', 'Minivan'), ('Convertible', 'Convertible'), ('Sport', 'Sport'), ('Electric', 'Electric')], max_length=50)),
                ('number_of_people_can_contain', models.SmallIntegerField()),
                ('contain_baby_seat', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('reserved', models.BooleanField(default=False)),
                ('car_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.carcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CarCompanyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('car_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.carcompany')),
            ],
        ),
    ]
