# Generated by Django 5.0 on 2024-03-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarCompany', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carcompanycomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carcompanyimages',
            name='car_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.carcompany'),
        ),
        migrations.AddField(
            model_name='carimages',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.car'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='car_company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.carcompany'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='car_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.car'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carreservationidimage',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarCompany.carreservation'),
        ),
    ]
