# Generated by Django 5.0 on 2024-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCompany', '0003_carcompanyadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
