# Generated by Django 5.0 on 2024-04-03 07:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCompany', '0004_alter_carreservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 7, 57, 0, 288344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
