# Generated by Django 5.0 on 2024-04-03 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCompany', '0006_alter_carreservation_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreservation',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 8, 6, 25, 256538, tzinfo=datetime.timezone.utc)),
        ),
    ]
